version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    #environment:
      #- MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      #- MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      #- MONGO_INITDB_DATABASE=project
  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=${MONGO_PORT}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      #- ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      #- ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_ROOT_USER}
      #- ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_ROOT_PASSWORD}
      #- ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      #- ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
    #Check how it works
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 10M
        reservations:
          cpus: '0.1'
          memory: 10M
    depends_on:
      - mongo
    ports:
      - "8081:8081"
